// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/health_check.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//Envoy cluster health check configuration
//
//See [envoy docs](https://www.envoyproxy.io/docs/envoy/v1.11.0/intro/arch_overview/upstream/health_checking#arch-overview-health-checking) for more information on how health checks work in envoy
//Or examine the [config definition](https://www.envoyproxy.io/docs/envoy/v1.11.0/api-v2/api/v2/core/health_check.proto#envoy-api-msg-core-healthcheck).
type HealthCheckConfig struct {
	Timeout  *time.Duration `protobuf:"bytes,1,opt,name=timeout,proto3,stdduration" json:"timeout,omitempty"`
	Interval *time.Duration `protobuf:"bytes,2,opt,name=interval,proto3,stdduration" json:"interval,omitempty"`
	// Types that are valid to be assigned to HealthChecker:
	//	*HealthCheckConfig_HttpHealthCheck_
	//	*HealthCheckConfig_GrpcHealthCheck_
	HealthChecker        isHealthCheckConfig_HealthChecker `protobuf_oneof:"health_checker"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckConfig) Reset()         { *m = HealthCheckConfig{} }
func (m *HealthCheckConfig) String() string { return proto.CompactTextString(m) }
func (*HealthCheckConfig) ProtoMessage()    {}
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca67440953dae5, []int{0}
}
func (m *HealthCheckConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckConfig.Unmarshal(m, b)
}
func (m *HealthCheckConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckConfig.Marshal(b, m, deterministic)
}
func (m *HealthCheckConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckConfig.Merge(m, src)
}
func (m *HealthCheckConfig) XXX_Size() int {
	return xxx_messageInfo_HealthCheckConfig.Size(m)
}
func (m *HealthCheckConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckConfig proto.InternalMessageInfo

type isHealthCheckConfig_HealthChecker interface {
	isHealthCheckConfig_HealthChecker()
	Equal(interface{}) bool
}

type HealthCheckConfig_HttpHealthCheck_ struct {
	HttpHealthCheck *HealthCheckConfig_HttpHealthCheck `protobuf:"bytes,8,opt,name=http_health_check,json=httpHealthCheck,proto3,oneof"`
}
type HealthCheckConfig_GrpcHealthCheck_ struct {
	GrpcHealthCheck *HealthCheckConfig_GrpcHealthCheck `protobuf:"bytes,11,opt,name=grpc_health_check,json=grpcHealthCheck,proto3,oneof"`
}

func (*HealthCheckConfig_HttpHealthCheck_) isHealthCheckConfig_HealthChecker() {}
func (*HealthCheckConfig_GrpcHealthCheck_) isHealthCheckConfig_HealthChecker() {}

func (m *HealthCheckConfig) GetHealthChecker() isHealthCheckConfig_HealthChecker {
	if m != nil {
		return m.HealthChecker
	}
	return nil
}

func (m *HealthCheckConfig) GetTimeout() *time.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *HealthCheckConfig) GetInterval() *time.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *HealthCheckConfig) GetHttpHealthCheck() *HealthCheckConfig_HttpHealthCheck {
	if x, ok := m.GetHealthChecker().(*HealthCheckConfig_HttpHealthCheck_); ok {
		return x.HttpHealthCheck
	}
	return nil
}

func (m *HealthCheckConfig) GetGrpcHealthCheck() *HealthCheckConfig_GrpcHealthCheck {
	if x, ok := m.GetHealthChecker().(*HealthCheckConfig_GrpcHealthCheck_); ok {
		return x.GrpcHealthCheck
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HealthCheckConfig) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HealthCheckConfig_OneofMarshaler, _HealthCheckConfig_OneofUnmarshaler, _HealthCheckConfig_OneofSizer, []interface{}{
		(*HealthCheckConfig_HttpHealthCheck_)(nil),
		(*HealthCheckConfig_GrpcHealthCheck_)(nil),
	}
}

func _HealthCheckConfig_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HealthCheckConfig)
	// health_checker
	switch x := m.HealthChecker.(type) {
	case *HealthCheckConfig_HttpHealthCheck_:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HttpHealthCheck); err != nil {
			return err
		}
	case *HealthCheckConfig_GrpcHealthCheck_:
		_ = b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GrpcHealthCheck); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HealthCheckConfig.HealthChecker has unexpected type %T", x)
	}
	return nil
}

func _HealthCheckConfig_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HealthCheckConfig)
	switch tag {
	case 8: // health_checker.http_health_check
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HealthCheckConfig_HttpHealthCheck)
		err := b.DecodeMessage(msg)
		m.HealthChecker = &HealthCheckConfig_HttpHealthCheck_{msg}
		return true, err
	case 11: // health_checker.grpc_health_check
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HealthCheckConfig_GrpcHealthCheck)
		err := b.DecodeMessage(msg)
		m.HealthChecker = &HealthCheckConfig_GrpcHealthCheck_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HealthCheckConfig_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HealthCheckConfig)
	// health_checker
	switch x := m.HealthChecker.(type) {
	case *HealthCheckConfig_HttpHealthCheck_:
		s := proto.Size(x.HttpHealthCheck)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HealthCheckConfig_GrpcHealthCheck_:
		s := proto.Size(x.GrpcHealthCheck)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HealthCheckConfig_HttpHealthCheck struct {
	// The value of the host header in the HTTP health check request. If
	// left empty (default value), the name of the cluster this health check is associated
	// with will be used.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Specifies the HTTP path that will be requested during health checking. For example
	// */healthcheck*.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// An optional service name parameter which is used to validate the identity of
	// the health checked cluster. See the :ref:`architecture overview
	// <arch_overview_health_checking_identity>` for more information.
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// If set, health checks will be made using http/2.
	UseHttp2             bool     `protobuf:"varint,7,opt,name=use_http2,json=useHttp2,proto3" json:"use_http2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckConfig_HttpHealthCheck) Reset()         { *m = HealthCheckConfig_HttpHealthCheck{} }
func (m *HealthCheckConfig_HttpHealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheckConfig_HttpHealthCheck) ProtoMessage()    {}
func (*HealthCheckConfig_HttpHealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca67440953dae5, []int{0, 0}
}
func (m *HealthCheckConfig_HttpHealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckConfig_HttpHealthCheck.Unmarshal(m, b)
}
func (m *HealthCheckConfig_HttpHealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckConfig_HttpHealthCheck.Marshal(b, m, deterministic)
}
func (m *HealthCheckConfig_HttpHealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckConfig_HttpHealthCheck.Merge(m, src)
}
func (m *HealthCheckConfig_HttpHealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheckConfig_HttpHealthCheck.Size(m)
}
func (m *HealthCheckConfig_HttpHealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckConfig_HttpHealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckConfig_HttpHealthCheck proto.InternalMessageInfo

func (m *HealthCheckConfig_HttpHealthCheck) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HealthCheckConfig_HttpHealthCheck) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *HealthCheckConfig_HttpHealthCheck) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *HealthCheckConfig_HttpHealthCheck) GetUseHttp2() bool {
	if m != nil {
		return m.UseHttp2
	}
	return false
}

// `grpc.health.v1.Health
// <https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto>`_-based
// healthcheck. See `gRPC doc <https://github.com/grpc/grpc/blob/master/doc/health-checking.md>`_
// for details.
type HealthCheckConfig_GrpcHealthCheck struct {
	// An optional service name parameter which will be sent to gRPC service in
	// `grpc.health.v1.HealthCheckRequest
	// <https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto#L20>`_.
	// message. See `gRPC health-checking overview
	// <https://github.com/grpc/grpc/blob/master/doc/health-checking.md>`_ for more information.
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// The value of the :authority header in the gRPC health check request. If
	// left empty (default value), the name of the cluster this health check is associated
	// with will be used.
	Authority            string   `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckConfig_GrpcHealthCheck) Reset()         { *m = HealthCheckConfig_GrpcHealthCheck{} }
func (m *HealthCheckConfig_GrpcHealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheckConfig_GrpcHealthCheck) ProtoMessage()    {}
func (*HealthCheckConfig_GrpcHealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_17ca67440953dae5, []int{0, 1}
}
func (m *HealthCheckConfig_GrpcHealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck.Unmarshal(m, b)
}
func (m *HealthCheckConfig_GrpcHealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck.Marshal(b, m, deterministic)
}
func (m *HealthCheckConfig_GrpcHealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck.Merge(m, src)
}
func (m *HealthCheckConfig_GrpcHealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck.Size(m)
}
func (m *HealthCheckConfig_GrpcHealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckConfig_GrpcHealthCheck proto.InternalMessageInfo

func (m *HealthCheckConfig_GrpcHealthCheck) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *HealthCheckConfig_GrpcHealthCheck) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthCheckConfig)(nil), "gloo.solo.io.HealthCheckConfig")
	proto.RegisterType((*HealthCheckConfig_HttpHealthCheck)(nil), "gloo.solo.io.HealthCheckConfig.HttpHealthCheck")
	proto.RegisterType((*HealthCheckConfig_GrpcHealthCheck)(nil), "gloo.solo.io.HealthCheckConfig.GrpcHealthCheck")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/health_check.proto", fileDescriptor_17ca67440953dae5)
}

var fileDescriptor_17ca67440953dae5 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x8b, 0x13, 0x31,
	0x14, 0xc7, 0xcd, 0xee, 0xac, 0xdb, 0x49, 0x17, 0xcb, 0x06, 0x61, 0xc7, 0xaa, 0x6b, 0xf5, 0xb4,
	0x17, 0x13, 0xad, 0x20, 0x88, 0x07, 0xa1, 0x2b, 0xd8, 0x93, 0x87, 0x39, 0x0a, 0x52, 0xd2, 0xd9,
	0x6c, 0x12, 0x77, 0xda, 0x17, 0x32, 0x6f, 0x2a, 0xde, 0xfd, 0x10, 0x7e, 0x04, 0x3f, 0x82, 0x08,
	0xc2, 0x7e, 0x13, 0xc1, 0x5b, 0xbf, 0x85, 0x4c, 0x66, 0xaa, 0xd3, 0x96, 0x85, 0xde, 0x5e, 0xfe,
	0x2f, 0xef, 0x37, 0xff, 0xf9, 0x93, 0x47, 0xdf, 0x68, 0x8b, 0xa6, 0x9c, 0xf2, 0x0c, 0x66, 0xa2,
	0x80, 0x1c, 0x9e, 0x5a, 0x10, 0x3a, 0x07, 0x10, 0xce, 0xc3, 0x27, 0x95, 0x61, 0x51, 0x9f, 0xa4,
	0xb3, 0x62, 0xf1, 0x5c, 0x18, 0x25, 0x73, 0x34, 0x93, 0xcc, 0xa8, 0xec, 0x8a, 0x3b, 0x0f, 0x08,
	0xec, 0xa8, 0xea, 0xf3, 0x6a, 0x94, 0x5b, 0xe8, 0x9f, 0x2c, 0x64, 0x6e, 0x2f, 0x24, 0x2a, 0xb1,
	0x2a, 0xea, 0x6b, 0xfd, 0xbb, 0x1a, 0x34, 0x84, 0x52, 0x54, 0x55, 0xa3, 0x9e, 0x6a, 0x00, 0x9d,
	0x2b, 0x11, 0x4e, 0xd3, 0xf2, 0x52, 0x7c, 0xf6, 0xd2, 0x39, 0xe5, 0x8b, 0x9b, 0xfa, 0x17, 0xa5,
	0x97, 0x68, 0x61, 0x5e, 0xf7, 0x9f, 0xfc, 0x8a, 0xe8, 0xf1, 0x38, 0x78, 0x3a, 0xaf, 0x2c, 0x9d,
	0xc3, 0xfc, 0xd2, 0x6a, 0xf6, 0x8a, 0x1e, 0xa2, 0x9d, 0x29, 0x28, 0x31, 0x21, 0x03, 0x72, 0xd6,
	0x1d, 0xde, 0xe3, 0x35, 0x87, 0xaf, 0x38, 0xfc, 0x6d, 0xc3, 0x19, 0x45, 0xdf, 0x7e, 0x3f, 0x22,
	0xe9, 0xea, 0x3e, 0x7b, 0x4d, 0x3b, 0x76, 0x8e, 0xca, 0x2f, 0x64, 0x9e, 0xec, 0xed, 0x36, 0xfb,
	0x6f, 0x80, 0x7d, 0xa4, 0xc7, 0x06, 0xd1, 0x4d, 0xda, 0x29, 0x25, 0x9d, 0x40, 0x11, 0xbc, 0x1d,
	0x13, 0xdf, 0xf2, 0xcc, 0xc7, 0x88, 0xae, 0xa5, 0x8e, 0x6f, 0xa5, 0x3d, 0xb3, 0x2e, 0x55, 0x78,
	0xed, 0x5d, 0xb6, 0x8e, 0xef, 0xee, 0x86, 0x7f, 0xe7, 0x5d, 0xb6, 0x81, 0xd7, 0xeb, 0x52, 0xff,
	0x2b, 0xa1, 0xbd, 0x0d, 0x17, 0x8c, 0xd1, 0xc8, 0x40, 0x51, 0xc7, 0x18, 0xa7, 0xa1, 0x66, 0x0f,
	0x69, 0xe4, 0x24, 0x9a, 0x10, 0x4f, 0x3c, 0x8a, 0x7f, 0x2e, 0xaf, 0xf7, 0x23, 0xbf, 0x37, 0x20,
	0x69, 0x90, 0xd9, 0x63, 0x7a, 0x54, 0x28, 0xbf, 0xb0, 0x99, 0x9a, 0xcc, 0xe5, 0x4c, 0x25, 0x07,
	0x61, 0xb4, 0xdb, 0x68, 0xef, 0xe5, 0x4c, 0xb1, 0xfb, 0x34, 0x2e, 0x0b, 0x35, 0xa9, 0xfe, 0x6f,
	0x98, 0x1c, 0x0e, 0xc8, 0x59, 0x27, 0xed, 0x94, 0x85, 0xaa, 0x3e, 0x3e, 0xec, 0xa7, 0xb4, 0xb7,
	0x61, 0x76, 0x0b, 0x49, 0xb6, 0x91, 0x0f, 0x68, 0x2c, 0x4b, 0x34, 0xe0, 0x2d, 0x7e, 0xa9, 0x9d,
	0xa5, 0xff, 0x85, 0xd1, 0x09, 0xbd, 0xd3, 0x0e, 0x4d, 0x79, 0x76, 0xf0, 0x63, 0x79, 0xbd, 0x4f,
	0x46, 0x2f, 0xbf, 0xff, 0x39, 0x25, 0x1f, 0x9e, 0xed, 0xb6, 0x03, 0xee, 0x4a, 0x37, 0x7b, 0x30,
	0xbd, 0x1d, 0x1e, 0xc3, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xba, 0xcf, 0xe1, 0x3e,
	0x03, 0x00, 0x00,
}

func (this *HealthCheckConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig)
	if !ok {
		that2, ok := that.(HealthCheckConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timeout != nil && that1.Timeout != nil {
		if *this.Timeout != *that1.Timeout {
			return false
		}
	} else if this.Timeout != nil {
		return false
	} else if that1.Timeout != nil {
		return false
	}
	if this.Interval != nil && that1.Interval != nil {
		if *this.Interval != *that1.Interval {
			return false
		}
	} else if this.Interval != nil {
		return false
	} else if that1.Interval != nil {
		return false
	}
	if that1.HealthChecker == nil {
		if this.HealthChecker != nil {
			return false
		}
	} else if this.HealthChecker == nil {
		return false
	} else if !this.HealthChecker.Equal(that1.HealthChecker) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HealthCheckConfig_HttpHealthCheck_) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig_HttpHealthCheck_)
	if !ok {
		that2, ok := that.(HealthCheckConfig_HttpHealthCheck_)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HttpHealthCheck.Equal(that1.HttpHealthCheck) {
		return false
	}
	return true
}
func (this *HealthCheckConfig_GrpcHealthCheck_) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig_GrpcHealthCheck_)
	if !ok {
		that2, ok := that.(HealthCheckConfig_GrpcHealthCheck_)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.GrpcHealthCheck.Equal(that1.GrpcHealthCheck) {
		return false
	}
	return true
}
func (this *HealthCheckConfig_HttpHealthCheck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig_HttpHealthCheck)
	if !ok {
		that2, ok := that.(HealthCheckConfig_HttpHealthCheck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Host != that1.Host {
		return false
	}
	if this.Path != that1.Path {
		return false
	}
	if this.ServiceName != that1.ServiceName {
		return false
	}
	if this.UseHttp2 != that1.UseHttp2 {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HealthCheckConfig_GrpcHealthCheck) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HealthCheckConfig_GrpcHealthCheck)
	if !ok {
		that2, ok := that.(HealthCheckConfig_GrpcHealthCheck)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ServiceName != that1.ServiceName {
		return false
	}
	if this.Authority != that1.Authority {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
