// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	als "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/als"
	aws "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/aws"
	ec2 "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/aws/ec2"
	azure "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/azure"
	consul "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/consul"
	cors "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/cors"
	faultinjection "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/faultinjection"
	grpc "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/grpc"
	grpc_web "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/grpc_web"
	hcm "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/hcm"
	headers "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/headers"
	hostrewrite "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/hostrewrite"
	kubernetes "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/kubernetes"
	lbhash "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/lbhash"
	pipe "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/pipe"
	rest "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/rest"
	retries "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/retries"
	shadowing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/shadowing"
	static "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/static"
	stats "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/stats"
	tcp "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/tcp"
	tracing "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/tracing"
	transformation "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/plugins/transformation"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Plugin-specific configuration that lives on gateways
// Each ListenerPlugin object contains configuration for a specific plugin
// Note to developers: new Listener Plugins must be added to this struct
// to be usable by Gloo.
type ListenerPlugins struct {
	AccessLoggingService *als.AccessLoggingService `protobuf:"bytes,1,opt,name=access_logging_service,json=accessLoggingService,proto3" json:"access_logging_service,omitempty"`
	Extensions           *Extensions               `protobuf:"bytes,2,opt,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListenerPlugins) Reset()         { *m = ListenerPlugins{} }
func (m *ListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*ListenerPlugins) ProtoMessage()    {}
func (*ListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{0}
}
func (m *ListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenerPlugins.Unmarshal(m, b)
}
func (m *ListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenerPlugins.Marshal(b, m, deterministic)
}
func (m *ListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenerPlugins.Merge(m, src)
}
func (m *ListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_ListenerPlugins.Size(m)
}
func (m *ListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_ListenerPlugins proto.InternalMessageInfo

func (m *ListenerPlugins) GetAccessLoggingService() *als.AccessLoggingService {
	if m != nil {
		return m.AccessLoggingService
	}
	return nil
}

func (m *ListenerPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

// Plugin-specific configuration that lives on http listeners
type HttpListenerPlugins struct {
	GrpcWeb                       *grpc_web.GrpcWeb                  `protobuf:"bytes,1,opt,name=grpc_web,json=grpcWeb,proto3" json:"grpc_web,omitempty"`
	HttpConnectionManagerSettings *hcm.HttpConnectionManagerSettings `protobuf:"bytes,2,opt,name=http_connection_manager_settings,json=httpConnectionManagerSettings,proto3" json:"http_connection_manager_settings,omitempty"`
	Extensions                    *Extensions                        `protobuf:"bytes,3,opt,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                           `json:"-"`
	XXX_unrecognized              []byte                             `json:"-"`
	XXX_sizecache                 int32                              `json:"-"`
}

func (m *HttpListenerPlugins) Reset()         { *m = HttpListenerPlugins{} }
func (m *HttpListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*HttpListenerPlugins) ProtoMessage()    {}
func (*HttpListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{1}
}
func (m *HttpListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpListenerPlugins.Unmarshal(m, b)
}
func (m *HttpListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpListenerPlugins.Marshal(b, m, deterministic)
}
func (m *HttpListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpListenerPlugins.Merge(m, src)
}
func (m *HttpListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_HttpListenerPlugins.Size(m)
}
func (m *HttpListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_HttpListenerPlugins proto.InternalMessageInfo

func (m *HttpListenerPlugins) GetGrpcWeb() *grpc_web.GrpcWeb {
	if m != nil {
		return m.GrpcWeb
	}
	return nil
}

func (m *HttpListenerPlugins) GetHttpConnectionManagerSettings() *hcm.HttpConnectionManagerSettings {
	if m != nil {
		return m.HttpConnectionManagerSettings
	}
	return nil
}

func (m *HttpListenerPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

// Plugin-specific configuration that lives on tcp listeners
type TcpListenerPlugins struct {
	TcpProxySettings     *tcp.TcpProxySettings `protobuf:"bytes,3,opt,name=tcp_proxy_settings,json=tcpProxySettings,proto3" json:"tcp_proxy_settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TcpListenerPlugins) Reset()         { *m = TcpListenerPlugins{} }
func (m *TcpListenerPlugins) String() string { return proto.CompactTextString(m) }
func (*TcpListenerPlugins) ProtoMessage()    {}
func (*TcpListenerPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{2}
}
func (m *TcpListenerPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpListenerPlugins.Unmarshal(m, b)
}
func (m *TcpListenerPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpListenerPlugins.Marshal(b, m, deterministic)
}
func (m *TcpListenerPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpListenerPlugins.Merge(m, src)
}
func (m *TcpListenerPlugins) XXX_Size() int {
	return xxx_messageInfo_TcpListenerPlugins.Size(m)
}
func (m *TcpListenerPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpListenerPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_TcpListenerPlugins proto.InternalMessageInfo

func (m *TcpListenerPlugins) GetTcpProxySettings() *tcp.TcpProxySettings {
	if m != nil {
		return m.TcpProxySettings
	}
	return nil
}

// Plugin-specific configuration that lives on virtual hosts
// Each VirtualHostPlugin object contains configuration for a specific plugin
// Note to developers: new Virtual Host Plugins must be added to this struct
// to be usable by Gloo.
type VirtualHostPlugins struct {
	Extensions *Extensions          `protobuf:"bytes,1,opt,name=extensions,proto3" json:"extensions,omitempty"`
	Retries    *retries.RetryPolicy `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Stats      *stats.Stats         `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	// Append/Remove headers on Requests or Responses on all routes contained in this Virtual Host
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,2,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Defines a CORS policy for the virtual host
	// If a CORS policy is also defined on the route matched by the request, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	// Transformations to apply
	Transformations      *transformation.RouteTransformations `protobuf:"bytes,4,opt,name=transformations,proto3" json:"transformations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *VirtualHostPlugins) Reset()         { *m = VirtualHostPlugins{} }
func (m *VirtualHostPlugins) String() string { return proto.CompactTextString(m) }
func (*VirtualHostPlugins) ProtoMessage()    {}
func (*VirtualHostPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{3}
}
func (m *VirtualHostPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualHostPlugins.Unmarshal(m, b)
}
func (m *VirtualHostPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualHostPlugins.Marshal(b, m, deterministic)
}
func (m *VirtualHostPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualHostPlugins.Merge(m, src)
}
func (m *VirtualHostPlugins) XXX_Size() int {
	return xxx_messageInfo_VirtualHostPlugins.Size(m)
}
func (m *VirtualHostPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualHostPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualHostPlugins proto.InternalMessageInfo

func (m *VirtualHostPlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *VirtualHostPlugins) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *VirtualHostPlugins) GetStats() *stats.Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *VirtualHostPlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *VirtualHostPlugins) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *VirtualHostPlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

// Plugin-specific configuration that lives on routes
// Each RoutePlugin object contains configuration for a specific plugin
// Note to developers: new Route Plugins must be added to this struct
// to be usable by Gloo.
type RoutePlugins struct {
	// Transformations to apply
	Transformations *transformation.RouteTransformations `protobuf:"bytes,1,opt,name=transformations,proto3" json:"transformations,omitempty"`
	Faults          *faultinjection.RouteFaults          `protobuf:"bytes,2,opt,name=faults,proto3" json:"faults,omitempty"`
	PrefixRewrite   *transformation.PrefixRewrite        `protobuf:"bytes,3,opt,name=prefix_rewrite,json=prefixRewrite,proto3" json:"prefix_rewrite,omitempty"`
	Timeout         *time.Duration                       `protobuf:"bytes,4,opt,name=timeout,proto3,stdduration" json:"timeout,omitempty"`
	Retries         *retries.RetryPolicy                 `protobuf:"bytes,5,opt,name=retries,proto3" json:"retries,omitempty"`
	Extensions      *Extensions                          `protobuf:"bytes,6,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// Defines route-specific tracing configuration.
	// See here for additional information on Envoy's tracing capabilities: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/tracing.html
	// See here for additional information about configuring tracing with Gloo: https://gloo.solo.io/user_guides/setup_options/observability/#tracing
	Tracing *tracing.RouteTracingSettings `protobuf:"bytes,7,opt,name=tracing,proto3" json:"tracing,omitempty"`
	// Specifies traffic shadowing configuration for the route.
	// See here for additional information on Envoy's shadowing capabilities: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-requestmirrorpolicy
	Shadowing *shadowing.RouteShadowing `protobuf:"bytes,8,opt,name=shadowing,proto3" json:"shadowing,omitempty"`
	// Append/Remove headers on Requests or Responses on this Route
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,9,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Rewrite the Host header for requests matched on this route
	HostRewrite *hostrewrite.HostRewrite `protobuf:"bytes,10,opt,name=host_rewrite,json=hostRewrite,proto3" json:"host_rewrite,omitempty"`
	// Defines a CORS policy for the route
	// If a CORS policy is also defined on the route's virtual host, the policies are merged.
	Cors *cors.CorsPolicy `protobuf:"bytes,11,opt,name=cors,proto3" json:"cors,omitempty"`
	// For routes served by a hashing load balancer, this defines the input to the hash key
	// Gloo configures Envoy with the first available RouteActionHashConfig among the following ordered list of providers:
	// - route, upstream, virtual service
	LbHash               *lbhash.RouteActionHashConfig `protobuf:"bytes,12,opt,name=lb_hash,json=lbHash,proto3" json:"lb_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *RoutePlugins) Reset()         { *m = RoutePlugins{} }
func (m *RoutePlugins) String() string { return proto.CompactTextString(m) }
func (*RoutePlugins) ProtoMessage()    {}
func (*RoutePlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{4}
}
func (m *RoutePlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutePlugins.Unmarshal(m, b)
}
func (m *RoutePlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutePlugins.Marshal(b, m, deterministic)
}
func (m *RoutePlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutePlugins.Merge(m, src)
}
func (m *RoutePlugins) XXX_Size() int {
	return xxx_messageInfo_RoutePlugins.Size(m)
}
func (m *RoutePlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutePlugins.DiscardUnknown(m)
}

var xxx_messageInfo_RoutePlugins proto.InternalMessageInfo

func (m *RoutePlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

func (m *RoutePlugins) GetFaults() *faultinjection.RouteFaults {
	if m != nil {
		return m.Faults
	}
	return nil
}

func (m *RoutePlugins) GetPrefixRewrite() *transformation.PrefixRewrite {
	if m != nil {
		return m.PrefixRewrite
	}
	return nil
}

func (m *RoutePlugins) GetTimeout() *time.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *RoutePlugins) GetRetries() *retries.RetryPolicy {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (m *RoutePlugins) GetExtensions() *Extensions {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *RoutePlugins) GetTracing() *tracing.RouteTracingSettings {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *RoutePlugins) GetShadowing() *shadowing.RouteShadowing {
	if m != nil {
		return m.Shadowing
	}
	return nil
}

func (m *RoutePlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *RoutePlugins) GetHostRewrite() *hostrewrite.HostRewrite {
	if m != nil {
		return m.HostRewrite
	}
	return nil
}

func (m *RoutePlugins) GetCors() *cors.CorsPolicy {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *RoutePlugins) GetLbHash() *lbhash.RouteActionHashConfig {
	if m != nil {
		return m.LbHash
	}
	return nil
}

// Configuration for Destinations that are tied to the UpstreamSpec or ServiceSpec on that destination
type DestinationSpec struct {
	// Note to developers: new DestinationSpecs must be added to this oneof field
	// to be usable by Gloo.
	//
	// Types that are valid to be assigned to DestinationType:
	//	*DestinationSpec_Aws
	//	*DestinationSpec_Azure
	//	*DestinationSpec_Rest
	//	*DestinationSpec_Grpc
	DestinationType      isDestinationSpec_DestinationType `protobuf_oneof:"destination_type"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *DestinationSpec) Reset()         { *m = DestinationSpec{} }
func (m *DestinationSpec) String() string { return proto.CompactTextString(m) }
func (*DestinationSpec) ProtoMessage()    {}
func (*DestinationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{5}
}
func (m *DestinationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestinationSpec.Unmarshal(m, b)
}
func (m *DestinationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestinationSpec.Marshal(b, m, deterministic)
}
func (m *DestinationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestinationSpec.Merge(m, src)
}
func (m *DestinationSpec) XXX_Size() int {
	return xxx_messageInfo_DestinationSpec.Size(m)
}
func (m *DestinationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DestinationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DestinationSpec proto.InternalMessageInfo

type isDestinationSpec_DestinationType interface {
	isDestinationSpec_DestinationType()
	Equal(interface{}) bool
}

type DestinationSpec_Aws struct {
	Aws *aws.DestinationSpec `protobuf:"bytes,1,opt,name=aws,proto3,oneof"`
}
type DestinationSpec_Azure struct {
	Azure *azure.DestinationSpec `protobuf:"bytes,2,opt,name=azure,proto3,oneof"`
}
type DestinationSpec_Rest struct {
	Rest *rest.DestinationSpec `protobuf:"bytes,3,opt,name=rest,proto3,oneof"`
}
type DestinationSpec_Grpc struct {
	Grpc *grpc.DestinationSpec `protobuf:"bytes,4,opt,name=grpc,proto3,oneof"`
}

func (*DestinationSpec_Aws) isDestinationSpec_DestinationType()   {}
func (*DestinationSpec_Azure) isDestinationSpec_DestinationType() {}
func (*DestinationSpec_Rest) isDestinationSpec_DestinationType()  {}
func (*DestinationSpec_Grpc) isDestinationSpec_DestinationType()  {}

func (m *DestinationSpec) GetDestinationType() isDestinationSpec_DestinationType {
	if m != nil {
		return m.DestinationType
	}
	return nil
}

func (m *DestinationSpec) GetAws() *aws.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *DestinationSpec) GetAzure() *azure.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Azure); ok {
		return x.Azure
	}
	return nil
}

func (m *DestinationSpec) GetRest() *rest.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Rest); ok {
		return x.Rest
	}
	return nil
}

func (m *DestinationSpec) GetGrpc() *grpc.DestinationSpec {
	if x, ok := m.GetDestinationType().(*DestinationSpec_Grpc); ok {
		return x.Grpc
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DestinationSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DestinationSpec_OneofMarshaler, _DestinationSpec_OneofUnmarshaler, _DestinationSpec_OneofSizer, []interface{}{
		(*DestinationSpec_Aws)(nil),
		(*DestinationSpec_Azure)(nil),
		(*DestinationSpec_Rest)(nil),
		(*DestinationSpec_Grpc)(nil),
	}
}

func _DestinationSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DestinationSpec)
	// destination_type
	switch x := m.DestinationType.(type) {
	case *DestinationSpec_Aws:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aws); err != nil {
			return err
		}
	case *DestinationSpec_Azure:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Azure); err != nil {
			return err
		}
	case *DestinationSpec_Rest:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rest); err != nil {
			return err
		}
	case *DestinationSpec_Grpc:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Grpc); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DestinationSpec.DestinationType has unexpected type %T", x)
	}
	return nil
}

func _DestinationSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DestinationSpec)
	switch tag {
	case 1: // destination_type.aws
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(aws.DestinationSpec)
		err := b.DecodeMessage(msg)
		m.DestinationType = &DestinationSpec_Aws{msg}
		return true, err
	case 2: // destination_type.azure
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(azure.DestinationSpec)
		err := b.DecodeMessage(msg)
		m.DestinationType = &DestinationSpec_Azure{msg}
		return true, err
	case 3: // destination_type.rest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(rest.DestinationSpec)
		err := b.DecodeMessage(msg)
		m.DestinationType = &DestinationSpec_Rest{msg}
		return true, err
	case 4: // destination_type.grpc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(grpc.DestinationSpec)
		err := b.DecodeMessage(msg)
		m.DestinationType = &DestinationSpec_Grpc{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DestinationSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DestinationSpec)
	// destination_type
	switch x := m.DestinationType.(type) {
	case *DestinationSpec_Aws:
		s := proto.Size(x.Aws)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DestinationSpec_Azure:
		s := proto.Size(x.Azure)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DestinationSpec_Rest:
		s := proto.Size(x.Rest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DestinationSpec_Grpc:
		s := proto.Size(x.Grpc)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Plugin-specific configuration that is applied when a specific weighted destination
// is selected for routing.
type WeightedDestinationPlugins struct {
	// Append/Remove headers on Requests or Responses to/from this Weighted Destination
	HeaderManipulation *headers.HeaderManipulation `protobuf:"bytes,1,opt,name=header_manipulation,json=headerManipulation,proto3" json:"header_manipulation,omitempty"`
	// Transformations to apply
	Transformations      *transformation.RouteTransformations `protobuf:"bytes,2,opt,name=transformations,proto3" json:"transformations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *WeightedDestinationPlugins) Reset()         { *m = WeightedDestinationPlugins{} }
func (m *WeightedDestinationPlugins) String() string { return proto.CompactTextString(m) }
func (*WeightedDestinationPlugins) ProtoMessage()    {}
func (*WeightedDestinationPlugins) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{6}
}
func (m *WeightedDestinationPlugins) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeightedDestinationPlugins.Unmarshal(m, b)
}
func (m *WeightedDestinationPlugins) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeightedDestinationPlugins.Marshal(b, m, deterministic)
}
func (m *WeightedDestinationPlugins) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeightedDestinationPlugins.Merge(m, src)
}
func (m *WeightedDestinationPlugins) XXX_Size() int {
	return xxx_messageInfo_WeightedDestinationPlugins.Size(m)
}
func (m *WeightedDestinationPlugins) XXX_DiscardUnknown() {
	xxx_messageInfo_WeightedDestinationPlugins.DiscardUnknown(m)
}

var xxx_messageInfo_WeightedDestinationPlugins proto.InternalMessageInfo

func (m *WeightedDestinationPlugins) GetHeaderManipulation() *headers.HeaderManipulation {
	if m != nil {
		return m.HeaderManipulation
	}
	return nil
}

func (m *WeightedDestinationPlugins) GetTransformations() *transformation.RouteTransformations {
	if m != nil {
		return m.Transformations
	}
	return nil
}

// Each upstream in Gloo has a type. Supported types include `static`, `kubernetes`, `aws`, `consul`, and more.
// Each upstream type is handled by a corresponding Gloo plugin.
type UpstreamSpec struct {
	SslConfig *UpstreamSslConfig `protobuf:"bytes,1,opt,name=ssl_config,json=sslConfig,proto3" json:"ssl_config,omitempty"`
	// Circuit breakers for this upstream. if not set, the defaults ones from the Gloo settings will be used.
	// if those are not set, [envoy's defaults](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster/circuit_breaker.proto#envoy-api-msg-cluster-circuitbreakers)
	// will be used.
	CircuitBreakers    *CircuitBreakerConfig `protobuf:"bytes,2,opt,name=circuit_breakers,json=circuitBreakers,proto3" json:"circuit_breakers,omitempty"`
	LoadBalancerConfig *LoadBalancerConfig   `protobuf:"bytes,3,opt,name=load_balancer_config,json=loadBalancerConfig,proto3" json:"load_balancer_config,omitempty"`
	ConnectionConfig   *ConnectionConfig     `protobuf:"bytes,4,opt,name=connection_config,json=connectionConfig,proto3" json:"connection_config,omitempty"`
	HealthChecks       []*HealthCheckConfig  `protobuf:"bytes,5,rep,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	OutlierDetection   *OutlierDetection     `protobuf:"bytes,6,opt,name=outlier_detection,json=outlierDetection,proto3" json:"outlier_detection,omitempty"`
	// Use http2 when communicating with this upstream
	// this field is evaluated `true` for upstreams
	// with a grpc service spec
	UseHttp2 bool `protobuf:"varint,7,opt,name=use_http2,json=useHttp2,proto3" json:"use_http2,omitempty"`
	// Note to developers: new Upstream Plugins must be added to this oneof field
	// to be usable by Gloo.
	//
	// Types that are valid to be assigned to UpstreamType:
	//	*UpstreamSpec_Kube
	//	*UpstreamSpec_Static
	//	*UpstreamSpec_Pipe
	//	*UpstreamSpec_Aws
	//	*UpstreamSpec_Azure
	//	*UpstreamSpec_Consul
	//	*UpstreamSpec_AwsEc2
	UpstreamType         isUpstreamSpec_UpstreamType `protobuf_oneof:"upstream_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpstreamSpec) Reset()         { *m = UpstreamSpec{} }
func (m *UpstreamSpec) String() string { return proto.CompactTextString(m) }
func (*UpstreamSpec) ProtoMessage()    {}
func (*UpstreamSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae47d2df5fad2a45, []int{7}
}
func (m *UpstreamSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamSpec.Unmarshal(m, b)
}
func (m *UpstreamSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamSpec.Marshal(b, m, deterministic)
}
func (m *UpstreamSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamSpec.Merge(m, src)
}
func (m *UpstreamSpec) XXX_Size() int {
	return xxx_messageInfo_UpstreamSpec.Size(m)
}
func (m *UpstreamSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamSpec.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamSpec proto.InternalMessageInfo

type isUpstreamSpec_UpstreamType interface {
	isUpstreamSpec_UpstreamType()
	Equal(interface{}) bool
}

type UpstreamSpec_Kube struct {
	Kube *kubernetes.UpstreamSpec `protobuf:"bytes,8,opt,name=kube,proto3,oneof"`
}
type UpstreamSpec_Static struct {
	Static *static.UpstreamSpec `protobuf:"bytes,9,opt,name=static,proto3,oneof"`
}
type UpstreamSpec_Pipe struct {
	Pipe *pipe.UpstreamSpec `protobuf:"bytes,10,opt,name=pipe,proto3,oneof"`
}
type UpstreamSpec_Aws struct {
	Aws *aws.UpstreamSpec `protobuf:"bytes,11,opt,name=aws,proto3,oneof"`
}
type UpstreamSpec_Azure struct {
	Azure *azure.UpstreamSpec `protobuf:"bytes,12,opt,name=azure,proto3,oneof"`
}
type UpstreamSpec_Consul struct {
	Consul *consul.UpstreamSpec `protobuf:"bytes,13,opt,name=consul,proto3,oneof"`
}
type UpstreamSpec_AwsEc2 struct {
	AwsEc2 *ec2.UpstreamSpec `protobuf:"bytes,14,opt,name=aws_ec2,json=awsEc2,proto3,oneof"`
}

func (*UpstreamSpec_Kube) isUpstreamSpec_UpstreamType()   {}
func (*UpstreamSpec_Static) isUpstreamSpec_UpstreamType() {}
func (*UpstreamSpec_Pipe) isUpstreamSpec_UpstreamType()   {}
func (*UpstreamSpec_Aws) isUpstreamSpec_UpstreamType()    {}
func (*UpstreamSpec_Azure) isUpstreamSpec_UpstreamType()  {}
func (*UpstreamSpec_Consul) isUpstreamSpec_UpstreamType() {}
func (*UpstreamSpec_AwsEc2) isUpstreamSpec_UpstreamType() {}

func (m *UpstreamSpec) GetUpstreamType() isUpstreamSpec_UpstreamType {
	if m != nil {
		return m.UpstreamType
	}
	return nil
}

func (m *UpstreamSpec) GetSslConfig() *UpstreamSslConfig {
	if m != nil {
		return m.SslConfig
	}
	return nil
}

func (m *UpstreamSpec) GetCircuitBreakers() *CircuitBreakerConfig {
	if m != nil {
		return m.CircuitBreakers
	}
	return nil
}

func (m *UpstreamSpec) GetLoadBalancerConfig() *LoadBalancerConfig {
	if m != nil {
		return m.LoadBalancerConfig
	}
	return nil
}

func (m *UpstreamSpec) GetConnectionConfig() *ConnectionConfig {
	if m != nil {
		return m.ConnectionConfig
	}
	return nil
}

func (m *UpstreamSpec) GetHealthChecks() []*HealthCheckConfig {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *UpstreamSpec) GetOutlierDetection() *OutlierDetection {
	if m != nil {
		return m.OutlierDetection
	}
	return nil
}

func (m *UpstreamSpec) GetUseHttp2() bool {
	if m != nil {
		return m.UseHttp2
	}
	return false
}

func (m *UpstreamSpec) GetKube() *kubernetes.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Kube); ok {
		return x.Kube
	}
	return nil
}

func (m *UpstreamSpec) GetStatic() *static.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Static); ok {
		return x.Static
	}
	return nil
}

func (m *UpstreamSpec) GetPipe() *pipe.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Pipe); ok {
		return x.Pipe
	}
	return nil
}

func (m *UpstreamSpec) GetAws() *aws.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Aws); ok {
		return x.Aws
	}
	return nil
}

func (m *UpstreamSpec) GetAzure() *azure.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Azure); ok {
		return x.Azure
	}
	return nil
}

func (m *UpstreamSpec) GetConsul() *consul.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_Consul); ok {
		return x.Consul
	}
	return nil
}

func (m *UpstreamSpec) GetAwsEc2() *ec2.UpstreamSpec {
	if x, ok := m.GetUpstreamType().(*UpstreamSpec_AwsEc2); ok {
		return x.AwsEc2
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpstreamSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpstreamSpec_OneofMarshaler, _UpstreamSpec_OneofUnmarshaler, _UpstreamSpec_OneofSizer, []interface{}{
		(*UpstreamSpec_Kube)(nil),
		(*UpstreamSpec_Static)(nil),
		(*UpstreamSpec_Pipe)(nil),
		(*UpstreamSpec_Aws)(nil),
		(*UpstreamSpec_Azure)(nil),
		(*UpstreamSpec_Consul)(nil),
		(*UpstreamSpec_AwsEc2)(nil),
	}
}

func _UpstreamSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpstreamSpec)
	// upstream_type
	switch x := m.UpstreamType.(type) {
	case *UpstreamSpec_Kube:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Kube); err != nil {
			return err
		}
	case *UpstreamSpec_Static:
		_ = b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Static); err != nil {
			return err
		}
	case *UpstreamSpec_Pipe:
		_ = b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pipe); err != nil {
			return err
		}
	case *UpstreamSpec_Aws:
		_ = b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aws); err != nil {
			return err
		}
	case *UpstreamSpec_Azure:
		_ = b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Azure); err != nil {
			return err
		}
	case *UpstreamSpec_Consul:
		_ = b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Consul); err != nil {
			return err
		}
	case *UpstreamSpec_AwsEc2:
		_ = b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AwsEc2); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UpstreamSpec.UpstreamType has unexpected type %T", x)
	}
	return nil
}

func _UpstreamSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpstreamSpec)
	switch tag {
	case 8: // upstream_type.kube
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(kubernetes.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Kube{msg}
		return true, err
	case 9: // upstream_type.static
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(static.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Static{msg}
		return true, err
	case 10: // upstream_type.pipe
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(pipe.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Pipe{msg}
		return true, err
	case 11: // upstream_type.aws
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(aws.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Aws{msg}
		return true, err
	case 12: // upstream_type.azure
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(azure.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Azure{msg}
		return true, err
	case 13: // upstream_type.consul
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(consul.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_Consul{msg}
		return true, err
	case 14: // upstream_type.aws_ec2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ec2.UpstreamSpec)
		err := b.DecodeMessage(msg)
		m.UpstreamType = &UpstreamSpec_AwsEc2{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UpstreamSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpstreamSpec)
	// upstream_type
	switch x := m.UpstreamType.(type) {
	case *UpstreamSpec_Kube:
		s := proto.Size(x.Kube)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_Static:
		s := proto.Size(x.Static)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_Pipe:
		s := proto.Size(x.Pipe)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_Aws:
		s := proto.Size(x.Aws)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_Azure:
		s := proto.Size(x.Azure)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_Consul:
		s := proto.Size(x.Consul)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UpstreamSpec_AwsEc2:
		s := proto.Size(x.AwsEc2)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ListenerPlugins)(nil), "gloo.solo.io.ListenerPlugins")
	proto.RegisterType((*HttpListenerPlugins)(nil), "gloo.solo.io.HttpListenerPlugins")
	proto.RegisterType((*TcpListenerPlugins)(nil), "gloo.solo.io.TcpListenerPlugins")
	proto.RegisterType((*VirtualHostPlugins)(nil), "gloo.solo.io.VirtualHostPlugins")
	proto.RegisterType((*RoutePlugins)(nil), "gloo.solo.io.RoutePlugins")
	proto.RegisterType((*DestinationSpec)(nil), "gloo.solo.io.DestinationSpec")
	proto.RegisterType((*WeightedDestinationPlugins)(nil), "gloo.solo.io.WeightedDestinationPlugins")
	proto.RegisterType((*UpstreamSpec)(nil), "gloo.solo.io.UpstreamSpec")
}

func init() {
	proto.RegisterFile("github.com/solo-io/gloo/projects/gloo/api/v1/plugins.proto", fileDescriptor_ae47d2df5fad2a45)
}

var fileDescriptor_ae47d2df5fad2a45 = []byte{
	// 1488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xdd, 0x6e, 0xdc, 0xb6,
	0x12, 0x3e, 0x6b, 0x3b, 0x5e, 0x9b, 0xb6, 0x63, 0x87, 0x09, 0x0e, 0xf6, 0xf8, 0x9c, 0x93, 0xa4,
	0x06, 0xda, 0xfc, 0x14, 0xe1, 0xa6, 0x5b, 0x20, 0x69, 0x02, 0xa4, 0x49, 0xbc, 0x4e, 0x6a, 0x34,
	0x4e, 0x63, 0xc8, 0x6e, 0x93, 0xf6, 0x46, 0xd0, 0x72, 0xb9, 0x12, 0x63, 0x59, 0x14, 0x48, 0xca,
	0x8e, 0x7b, 0xd5, 0x97, 0x28, 0xda, 0x47, 0xe8, 0x4d, 0x2f, 0xfa, 0x0e, 0x7d, 0x82, 0xde, 0xf5,
	0xaa, 0x40, 0x9f, 0xa4, 0x20, 0x39, 0xd2, 0xee, 0xca, 0x72, 0xb0, 0x3f, 0xbe, 0x90, 0x44, 0x91,
	0x33, 0x9f, 0x86, 0xc3, 0x99, 0x8f, 0x43, 0xa1, 0x87, 0x21, 0xd7, 0x51, 0xd6, 0x21, 0x54, 0x1c,
	0x36, 0x95, 0x88, 0xc5, 0x1d, 0x2e, 0x9a, 0x61, 0x2c, 0x44, 0x33, 0x95, 0xe2, 0x2d, 0xa3, 0x5a,
	0xb9, 0xb7, 0x20, 0xe5, 0xcd, 0xa3, 0x4f, 0x9a, 0x69, 0x9c, 0x85, 0x3c, 0x51, 0x24, 0x95, 0x42,
	0x0b, 0xbc, 0x6c, 0x86, 0x88, 0xd1, 0x22, 0x5c, 0xac, 0xff, 0x2f, 0x14, 0x22, 0x8c, 0x59, 0xd3,
	0x8e, 0x75, 0xb2, 0x5e, 0x53, 0x69, 0x99, 0x51, 0xed, 0x64, 0xd7, 0xaf, 0x84, 0x22, 0x14, 0xb6,
	0xd9, 0x34, 0x2d, 0xe8, 0xbd, 0x37, 0xd6, 0xd7, 0x95, 0x8a, 0x41, 0xef, 0xd1, 0x58, 0x7a, 0xec,
	0x9d, 0x66, 0x89, 0xe2, 0x22, 0x37, 0x7c, 0x7d, 0x73, 0x2c, 0x75, 0xca, 0x25, 0xcd, 0xb8, 0xf6,
	0x3b, 0x92, 0x05, 0x07, 0x4c, 0x02, 0xc6, 0x93, 0xb1, 0x30, 0x62, 0x11, 0x74, 0xfd, 0x4e, 0x10,
	0x07, 0x09, 0x2d, 0x10, 0x1e, 0x8f, 0x85, 0x10, 0xb1, 0x20, 0xd6, 0x91, 0x4f, 0x23, 0x46, 0x0f,
	0x26, 0xf2, 0x02, 0x15, 0x49, 0xc2, 0xa8, 0xe6, 0x22, 0x99, 0xc8, 0x0b, 0xb0, 0xf4, 0xcd, 0xe0,
	0xd8, 0x5e, 0x80, 0xf1, 0xe5, 0xc4, 0x18, 0x8c, 0xb6, 0xcc, 0xd3, 0x67, 0xb4, 0x05, 0x58, 0x5b,
	0x13, 0x61, 0x51, 0x21, 0xdd, 0x6d, 0x2a, 0x14, 0xc9, 0x94, 0xb6, 0xb7, 0xa9, 0x50, 0x42, 0x99,
	0x52, 0x7b, 0x9b, 0xce, 0xc3, 0xb1, 0xbd, 0x00, 0x63, 0x67, 0x62, 0x4b, 0xfc, 0x63, 0xd6, 0x29,
	0x1a, 0x53, 0x59, 0x14, 0xd1, 0x43, 0x73, 0x01, 0xc6, 0xf6, 0x44, 0x18, 0x71, 0x27, 0x0a, 0x54,
	0x04, 0x0f, 0x40, 0xfa, 0x6a, 0x22, 0x24, 0x15, 0x05, 0x5d, 0x71, 0xcc, 0x93, 0xb0, 0xdf, 0x9a,
	0x6a, 0x76, 0x9a, 0xa6, 0xe6, 0x9a, 0x2a, 0xa2, 0xb5, 0x0c, 0xa8, 0xb1, 0x08, 0x9e, 0x80, 0xf5,
	0x7c, 0xb2, 0xf5, 0xff, 0x3e, 0x93, 0xcc, 0xdd, 0xa7, 0xf2, 0x38, 0x15, 0x89, 0xca, 0x62, 0x78,
	0x00, 0xd2, 0xee, 0x44, 0x48, 0x07, 0x59, 0x87, 0xc9, 0x84, 0x69, 0x36, 0xd8, 0x9c, 0xca, 0x5f,
	0x92, 0x69, 0xc9, 0x59, 0xf1, 0x9c, 0x6a, 0x9e, 0x4a, 0x07, 0x9a, 0x53, 0x78, 0x4c, 0x95, 0xbf,
	0x29, 0x4f, 0x99, 0xbd, 0x4d, 0xb5, 0x7e, 0xc6, 0x10, 0xb8, 0x03, 0xce, 0x9b, 0x49, 0x63, 0x2a,
	0x51, 0x3d, 0x21, 0x0f, 0x03, 0x43, 0xda, 0xcd, 0x54, 0xb2, 0x1e, 0x7f, 0xe7, 0x4b, 0x76, 0x2c,
	0xb9, 0x66, 0xe7, 0x89, 0x3c, 0xfc, 0x0a, 0xc8, 0xaf, 0x26, 0x42, 0xee, 0x05, 0x59, 0xac, 0x79,
	0xf2, 0xd6, 0x6d, 0x34, 0xee, 0x75, 0xaa, 0x40, 0x89, 0x58, 0xd0, 0x65, 0xb2, 0x78, 0x02, 0x96,
	0x37, 0x19, 0x96, 0x50, 0x1a, 0xdc, 0x37, 0xd8, 0x06, 0xcc, 0xab, 0xe5, 0xfa, 0xa5, 0x9b, 0xc9,
	0x01, 0x87, 0x6c, 0xfc, 0x56, 0x43, 0xab, 0x3b, 0x5c, 0x69, 0x96, 0x30, 0xb9, 0xeb, 0x10, 0x71,
	0x17, 0xfd, 0x3b, 0xa0, 0x94, 0x29, 0xe5, 0xc7, 0x22, 0x0c, 0x79, 0x12, 0xfa, 0x8a, 0xc9, 0x23,
	0x4e, 0x59, 0xa3, 0x76, 0xbd, 0x76, 0x73, 0xa9, 0x45, 0x88, 0x25, 0x72, 0xa8, 0x9a, 0x06, 0xcb,
	0x25, 0xf2, 0xd4, 0xea, 0xed, 0x38, 0xb5, 0x3d, 0xa7, 0xe5, 0x5d, 0x09, 0x2a, 0x7a, 0xf1, 0x67,
	0x08, 0xf5, 0x4b, 0x98, 0xc6, 0x8c, 0x45, 0x6e, 0x0c, 0xa3, 0x3d, 0x2b, 0xc6, 0xbd, 0x01, 0xd9,
	0x8d, 0x1f, 0x67, 0xd0, 0xe5, 0x6d, 0xad, 0xd3, 0xb2, 0xdd, 0x4f, 0xd1, 0x42, 0xbe, 0x31, 0x80,
	0xa5, 0x1f, 0x91, 0xfe, 0x4e, 0x51, 0x65, 0xee, 0x17, 0x32, 0xa5, 0xaf, 0x59, 0xc7, 0xab, 0x87,
	0xae, 0x81, 0x7f, 0xa8, 0xa1, 0xeb, 0x91, 0xd6, 0xa9, 0xdf, 0xaf, 0x2b, 0xfc, 0xc3, 0x20, 0x09,
	0x42, 0x26, 0x7d, 0xc5, 0xb4, 0xe6, 0x49, 0x98, 0xdb, 0x7a, 0x9f, 0xd8, 0xcd, 0xa3, 0x0a, 0xd6,
	0x18, 0xd7, 0x2e, 0x00, 0x5e, 0x3a, 0xfd, 0x3d, 0x50, 0xf7, 0xfe, 0x1f, 0xbd, 0x6f, 0xb8, 0xe4,
	0x97, 0xd9, 0x31, 0xfc, 0x92, 0x20, 0xbc, 0x4f, 0x4f, 0x79, 0xe5, 0x0d, 0xc2, 0x9a, 0xa6, 0x7e,
	0x2a, 0xc5, 0xbb, 0x93, 0xfe, 0x1c, 0x1c, 0xee, 0x6d, 0x62, 0xb7, 0x88, 0xaa, 0x39, 0xec, 0xd3,
	0x74, 0xd7, 0xa8, 0x14, 0x66, 0xaf, 0xe9, 0x52, 0xcf, 0xc6, 0xef, 0xb3, 0x08, 0x7f, 0xc3, 0xa5,
	0xce, 0x82, 0x78, 0x5b, 0x28, 0x9d, 0x7f, 0x70, 0x78, 0x02, 0xb5, 0xd1, 0x27, 0x80, 0xdb, 0xa8,
	0x0e, 0xd4, 0xd9, 0xb8, 0x60, 0xd5, 0x6e, 0x91, 0x82, 0x4a, 0xab, 0x6c, 0xf4, 0x98, 0x96, 0x27,
	0xbb, 0x22, 0xe6, 0xf4, 0xc4, 0xcb, 0x35, 0xf1, 0x7d, 0x74, 0xc1, 0xb2, 0x54, 0x03, 0x59, 0x88,
	0x0f, 0x08, 0x70, 0x56, 0x15, 0xc0, 0x9e, 0x19, 0xf2, 0x9c, 0x3c, 0x0e, 0xd0, 0x65, 0x97, 0x8f,
	0x66, 0xc5, 0x79, 0x9a, 0xc5, 0x36, 0x4f, 0x60, 0xb5, 0xef, 0x92, 0x22, 0x57, 0x2b, 0x57, 0xdc,
	0x0e, 0xbe, 0x1c, 0xd0, 0xf3, 0x70, 0x74, 0xaa, 0x0f, 0x3f, 0x40, 0x73, 0xa6, 0xa8, 0x03, 0xef,
	0x7f, 0x48, 0x5c, 0x85, 0x57, 0x05, 0xd8, 0x16, 0x52, 0xc1, 0xcc, 0xac, 0x0a, 0x7e, 0x83, 0x56,
	0x87, 0x19, 0x4d, 0x35, 0xe6, 0x20, 0x1b, 0x59, 0x72, 0x24, 0x4e, 0x48, 0x90, 0x72, 0x72, 0xd4,
	0x22, 0x3d, 0x1e, 0x6b, 0x26, 0x89, 0x89, 0x31, 0xe2, 0x89, 0x4c, 0xb3, 0xfd, 0x61, 0x2d, 0xaf,
	0x0c, 0xb3, 0xf1, 0x53, 0x1d, 0x2d, 0x5b, 0xc9, 0x7e, 0xc4, 0x9c, 0xfa, 0x54, 0xed, 0x5c, 0x3e,
	0x85, 0x1f, 0xa3, 0x79, 0x4b, 0x9e, 0x79, 0x0e, 0xdd, 0x20, 0xc0, 0xa5, 0x95, 0xab, 0x6b, 0x20,
	0x9f, 0x5b, 0x71, 0x0f, 0xd4, 0xf0, 0xb7, 0xe8, 0xe2, 0xf0, 0x8e, 0x01, 0xae, 0x6c, 0x91, 0x32,
	0xdd, 0x57, 0x21, 0xee, 0x5a, 0x55, 0xcf, 0x69, 0x7a, 0x2b, 0xe9, 0xe0, 0x2b, 0x7e, 0x80, 0xea,
	0x9a, 0x1f, 0x32, 0x91, 0x69, 0x70, 0xec, 0x7f, 0x88, 0xe3, 0x4e, 0x92, 0x73, 0x27, 0xd9, 0x02,
	0xee, 0xdc, 0x9c, 0xfb, 0xf9, 0xaf, 0x6b, 0x35, 0x2f, 0x97, 0x3f, 0x9f, 0xb8, 0x1d, 0x4e, 0x9b,
	0xf9, 0x31, 0xd2, 0x66, 0x07, 0xd5, 0xa1, 0x42, 0x6b, 0xd4, 0xfb, 0xde, 0x70, 0x15, 0xdb, 0x99,
	0x8e, 0xdd, 0x77, 0x12, 0x45, 0x7a, 0xe7, 0x10, 0x78, 0x07, 0x2d, 0x16, 0x15, 0x68, 0x63, 0x01,
	0xd6, 0x7d, 0xa0, 0x26, 0x3d, 0x13, 0x71, 0x2f, 0x97, 0xf1, 0xfa, 0x00, 0x67, 0x25, 0xd5, 0xe2,
	0x39, 0x26, 0xd5, 0x2e, 0x5a, 0x36, 0xfb, 0x5e, 0x11, 0x11, 0x2e, 0xef, 0xef, 0x90, 0xa1, 0xcd,
	0xb0, 0x12, 0x5f, 0x28, 0x9d, 0x07, 0xc3, 0x52, 0xd4, 0x7f, 0x29, 0xd2, 0x74, 0x69, 0xfc, 0x34,
	0x7d, 0x81, 0xea, 0x71, 0xc7, 0x37, 0xa7, 0x81, 0xc6, 0x32, 0xac, 0x45, 0x7e, 0x38, 0x38, 0xd3,
	0x71, 0x4f, 0xed, 0x3e, 0xb0, 0x1d, 0xa8, 0xa8, 0x2d, 0x92, 0x1e, 0x0f, 0xbd, 0xf9, 0xb8, 0x63,
	0xde, 0x36, 0x7e, 0x9d, 0x41, 0xab, 0x5b, 0x4c, 0x69, 0x9e, 0xd8, 0x99, 0xee, 0xa5, 0x8c, 0xe2,
	0x47, 0x68, 0x36, 0x38, 0xce, 0x13, 0xf2, 0x16, 0xb1, 0x87, 0xd6, 0x2a, 0xe4, 0x92, 0xde, 0xf6,
	0xbf, 0x3c, 0xa3, 0x87, 0xdb, 0xe8, 0x82, 0xad, 0xc1, 0x21, 0x01, 0x3f, 0x26, 0x50, 0x91, 0x8f,
	0x06, 0xe1, 0x74, 0xf1, 0x13, 0x34, 0x67, 0x4e, 0x95, 0xc5, 0x26, 0xe2, 0x8e, 0x98, 0xa3, 0x41,
	0x58, 0x4d, 0x83, 0x60, 0xb6, 0x5c, 0xc8, 0xb4, 0xdb, 0xc4, 0x1d, 0x2f, 0x47, 0x44, 0x30, 0xc2,
	0x9b, 0x18, 0xad, 0x75, 0xfb, 0x43, 0xbe, 0x3e, 0x49, 0xd9, 0xc6, 0x9f, 0x35, 0xb4, 0xfe, 0x9a,
	0xf1, 0x30, 0xd2, 0xac, 0x3b, 0xa0, 0x97, 0xf3, 0xda, 0x19, 0xb1, 0x58, 0x3b, 0xc7, 0x58, 0xac,
	0xa0, 0xce, 0x99, 0xf3, 0x61, 0xe9, 0x3f, 0xea, 0x68, 0xf9, 0xeb, 0xd4, 0x44, 0x74, 0x70, 0x68,
	0x03, 0xe1, 0x73, 0x84, 0x94, 0x8a, 0x4d, 0xa1, 0xd2, 0xe3, 0x21, 0x4c, 0xe2, 0xda, 0xb0, 0xd1,
	0x85, 0xbc, 0x8a, 0x21, 0xb2, 0x16, 0x55, 0xde, 0xc4, 0x2f, 0xd1, 0x5a, 0xe9, 0x1f, 0x50, 0x6e,
	0xeb, 0x46, 0x29, 0xc6, 0x9d, 0xd4, 0xa6, 0x13, 0x02, 0xa0, 0x55, 0x3a, 0xd4, 0xab, 0xb0, 0x87,
	0xae, 0x0c, 0xfd, 0x0e, 0xca, 0x0d, 0x73, 0x31, 0x72, 0x7d, 0x18, 0x72, 0x47, 0x04, 0xdd, 0x4d,
	0x10, 0x04, 0x40, 0x1c, 0x9f, 0xea, 0xc3, 0x2f, 0xd0, 0xa5, 0x81, 0x3a, 0x0c, 0x00, 0x5d, 0xc8,
	0x5c, 0x2d, 0xe7, 0x61, 0x2e, 0x06, 0x70, 0x6b, 0xb4, 0xd4, 0x83, 0xb7, 0xd0, 0xca, 0xe0, 0xdf,
	0x26, 0x43, 0xd5, 0xb3, 0xa7, 0x5d, 0xb6, 0x6d, 0x45, 0xda, 0x46, 0x02, 0x90, 0x96, 0xa3, 0x7e,
	0x97, 0xc9, 0xef, 0x4b, 0x22, 0xd3, 0x31, 0x67, 0xd2, 0xef, 0x32, 0xed, 0x3e, 0x00, 0x64, 0x5d,
	0x32, 0xe9, 0x95, 0x13, 0xdb, 0xca, 0xa5, 0xbc, 0x35, 0x51, 0xea, 0xc1, 0xff, 0x45, 0x8b, 0x99,
	0x62, 0xbe, 0x89, 0x82, 0x96, 0xa5, 0xee, 0x05, 0x6f, 0x21, 0x53, 0xcc, 0x94, 0x8f, 0x2d, 0xdc,
	0x46, 0x73, 0xe6, 0x58, 0x0a, 0x14, 0x7c, 0x87, 0x0c, 0x9e, 0x51, 0xab, 0x22, 0x74, 0x30, 0x38,
	0x4c, 0x96, 0x18, 0x79, 0xdc, 0x46, 0xf3, 0xee, 0x04, 0x09, 0x8c, 0x7b, 0x8b, 0xe4, 0x07, 0xca,
	0x11, 0x20, 0x40, 0x15, 0x3f, 0x42, 0x73, 0xe6, 0xf8, 0x08, 0xc4, 0x7a, 0x83, 0xb8, 0xb3, 0xe4,
	0x28, 0x36, 0x18, 0x49, 0xfc, 0xd0, 0x31, 0xd6, 0x12, 0x54, 0xe4, 0x67, 0x32, 0x56, 0x49, 0xd9,
	0xd2, 0xd5, 0x93, 0x9c, 0xae, 0x1c, 0x99, 0xde, 0x7c, 0x1f, 0x5d, 0x95, 0xf4, 0x81, 0xab, 0xda,
	0x68, 0xde, 0xfd, 0x2b, 0x68, 0xac, 0x80, 0x07, 0xf2, 0x5f, 0x07, 0xa3, 0x78, 0xc0, 0xc9, 0xe2,
	0x67, 0xa8, 0x0e, 0x7f, 0xf5, 0x1a, 0x17, 0x81, 0xb1, 0x8a, 0xbf, 0x7c, 0xa3, 0xc0, 0x04, 0xc7,
	0xea, 0x19, 0x6d, 0x6d, 0xae, 0xa2, 0x95, 0x0c, 0x46, 0x2c, 0x61, 0x6d, 0xde, 0xfb, 0xe5, 0xef,
	0xab, 0xb5, 0xef, 0xee, 0x8e, 0x76, 0xee, 0x4b, 0x0f, 0x42, 0x38, 0xfb, 0x75, 0xe6, 0x6d, 0x49,
	0xf2, 0xe9, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x63, 0xa4, 0x5f, 0xe8, 0x16, 0x00, 0x00,
}

func (this *ListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListenerPlugins)
	if !ok {
		that2, ok := that.(ListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AccessLoggingService.Equal(that1.AccessLoggingService) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HttpListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HttpListenerPlugins)
	if !ok {
		that2, ok := that.(HttpListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.GrpcWeb.Equal(that1.GrpcWeb) {
		return false
	}
	if !this.HttpConnectionManagerSettings.Equal(that1.HttpConnectionManagerSettings) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *TcpListenerPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TcpListenerPlugins)
	if !ok {
		that2, ok := that.(TcpListenerPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TcpProxySettings.Equal(that1.TcpProxySettings) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *VirtualHostPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VirtualHostPlugins)
	if !ok {
		that2, ok := that.(VirtualHostPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Stats.Equal(that1.Stats) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RoutePlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RoutePlugins)
	if !ok {
		that2, ok := that.(RoutePlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !this.Faults.Equal(that1.Faults) {
		return false
	}
	if !this.PrefixRewrite.Equal(that1.PrefixRewrite) {
		return false
	}
	if this.Timeout != nil && that1.Timeout != nil {
		if *this.Timeout != *that1.Timeout {
			return false
		}
	} else if this.Timeout != nil {
		return false
	} else if that1.Timeout != nil {
		return false
	}
	if !this.Retries.Equal(that1.Retries) {
		return false
	}
	if !this.Extensions.Equal(that1.Extensions) {
		return false
	}
	if !this.Tracing.Equal(that1.Tracing) {
		return false
	}
	if !this.Shadowing.Equal(that1.Shadowing) {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.HostRewrite.Equal(that1.HostRewrite) {
		return false
	}
	if !this.Cors.Equal(that1.Cors) {
		return false
	}
	if !this.LbHash.Equal(that1.LbHash) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DestinationSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec)
	if !ok {
		that2, ok := that.(DestinationSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.DestinationType == nil {
		if this.DestinationType != nil {
			return false
		}
	} else if this.DestinationType == nil {
		return false
	} else if !this.DestinationType.Equal(that1.DestinationType) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DestinationSpec_Aws) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Aws)
	if !ok {
		that2, ok := that.(DestinationSpec_Aws)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Aws.Equal(that1.Aws) {
		return false
	}
	return true
}
func (this *DestinationSpec_Azure) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Azure)
	if !ok {
		that2, ok := that.(DestinationSpec_Azure)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Azure.Equal(that1.Azure) {
		return false
	}
	return true
}
func (this *DestinationSpec_Rest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Rest)
	if !ok {
		that2, ok := that.(DestinationSpec_Rest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Rest.Equal(that1.Rest) {
		return false
	}
	return true
}
func (this *DestinationSpec_Grpc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DestinationSpec_Grpc)
	if !ok {
		that2, ok := that.(DestinationSpec_Grpc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Grpc.Equal(that1.Grpc) {
		return false
	}
	return true
}
func (this *WeightedDestinationPlugins) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WeightedDestinationPlugins)
	if !ok {
		that2, ok := that.(WeightedDestinationPlugins)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.HeaderManipulation.Equal(that1.HeaderManipulation) {
		return false
	}
	if !this.Transformations.Equal(that1.Transformations) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *UpstreamSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec)
	if !ok {
		that2, ok := that.(UpstreamSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SslConfig.Equal(that1.SslConfig) {
		return false
	}
	if !this.CircuitBreakers.Equal(that1.CircuitBreakers) {
		return false
	}
	if !this.LoadBalancerConfig.Equal(that1.LoadBalancerConfig) {
		return false
	}
	if !this.ConnectionConfig.Equal(that1.ConnectionConfig) {
		return false
	}
	if len(this.HealthChecks) != len(that1.HealthChecks) {
		return false
	}
	for i := range this.HealthChecks {
		if !this.HealthChecks[i].Equal(that1.HealthChecks[i]) {
			return false
		}
	}
	if !this.OutlierDetection.Equal(that1.OutlierDetection) {
		return false
	}
	if this.UseHttp2 != that1.UseHttp2 {
		return false
	}
	if that1.UpstreamType == nil {
		if this.UpstreamType != nil {
			return false
		}
	} else if this.UpstreamType == nil {
		return false
	} else if !this.UpstreamType.Equal(that1.UpstreamType) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Kube) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Kube)
	if !ok {
		that2, ok := that.(UpstreamSpec_Kube)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Kube.Equal(that1.Kube) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Static) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Static)
	if !ok {
		that2, ok := that.(UpstreamSpec_Static)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Static.Equal(that1.Static) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Pipe) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Pipe)
	if !ok {
		that2, ok := that.(UpstreamSpec_Pipe)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Pipe.Equal(that1.Pipe) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Aws) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Aws)
	if !ok {
		that2, ok := that.(UpstreamSpec_Aws)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Aws.Equal(that1.Aws) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Azure) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Azure)
	if !ok {
		that2, ok := that.(UpstreamSpec_Azure)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Azure.Equal(that1.Azure) {
		return false
	}
	return true
}
func (this *UpstreamSpec_Consul) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_Consul)
	if !ok {
		that2, ok := that.(UpstreamSpec_Consul)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Consul.Equal(that1.Consul) {
		return false
	}
	return true
}
func (this *UpstreamSpec_AwsEc2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpstreamSpec_AwsEc2)
	if !ok {
		that2, ok := that.(UpstreamSpec_AwsEc2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.AwsEc2.Equal(that1.AwsEc2) {
		return false
	}
	return true
}
