apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  labels:
    app: gloo
    gloo: settings
  name: default
  namespace: "gloo-system"
spec:
  gloo:
    xdsBindAddr: 0.0.0.0:9977
    validationBindAddr: 0.0.0.0:9988
  gateway:
    validationServerAddr: gloo:9988 # Refers to the validationBindAddr above
    disableAutoGenGateways: true
    validation:
      alwaysAccept: false
      proxyValidationServerAddr: gloo:9988
      ignoreGlooValidationFailure: false # If gloo is offline all resources are rejected. If you want to disable that behaviour, set to true.
  discovery:
    fdsMode: "WHITELIST" # Only perform function discovery if we want it to
  discoveryNamespace: gloo-system
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  refreshRate: 60s
  watchNamespaces:
  - staging
  - production
  - monitoring
  - gloo-system     # This will be watched anyway since "discoveryNamespace" is set to gloo-system
  - private-ingress # Gloo needs access to any namespace with proxies running
  - public-ingress  # Same here
status: {}
